describe('Veryfying the checkout', () => {
    it('Should proceed to checkout', () => {
      cy.visit('https://www.saucedemo.com/')
      cy.get('[data-test="username"]').type("standard_user")
      cy.get('[data-test="password"]').type("secret_sauce")
      cy.get('[data-test="login-button"]').click()
      cy.get('.title').should('contain','Products')
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
      cy.get('.shopping_cart_badge').should('contain', '2')
      cy.get('.shopping_cart_link').click()
      cy.get('.shopping_cart_badge').should('contain' , '2')
      cy.get('#item_4_title_link > .inventory_item_name').should('contain' , 'Sauce Labs Backpack')
      cy.get('#item_0_title_link > .inventory_item_name').should('contain' , 'Sauce Labs Bike Light')
      cy.get('[data-test="checkout"]').click()
      cy.get('[data-test="firstName"]').type('test')
      cy.get('[data-test="lastName"]').type('test')
      cy.get('[data-test="postalCode"]').type('test')
      cy.get('[data-test="continue"]').click()
      cy.get('.cart_list > :nth-child(3)').should('contain', 'Sauce Labs Backpack')
      cy.get('.cart_list > :nth-child(4)').should('contain', 'Sauce Labs Bike Light')
      cy.get('.summary_subtotal_label').should('contain', 'Item total')
      cy.get('.summary_tax_label').should('contain' , 'Tax')
      cy.get('[data-test="finish"]').click()
      cy.get('#checkout_complete_container').should('contain', 'Thank you for your order!')
    })
})